### ISSUE TITLE
U+2013 Adobe-CNS CID120,121

### ISSUE THREAD

**Issue by t-tk** [trueroad/HaranoAjiFontsTW#1]
お世話になります。
Adobe-CNS1-7 では U+2013  EN DASH 「–」が H: CID121, V: CID120 にマップされ全角幅のようです。
HaranoAji TW でも出ることを期待したのですが豆腐になりました。
SourceHan に存在しないなどの理由でしょうか？

約物は伏魔殿というのをある程度覚悟していましたが想像以上でした😣
多分この件が最後だと思います…

**Comment by trueroad** [comment]
豆腐になりますか？
HaranoAji{Mincho|Gothic}TW-Regular 20220211 は AC1 CID+121, CID+120 ともに搭載しています。ただし SourceHan{Serif|Sans}TW の GSUB が U+2013 のグリフに対して vert がないため原ノ味TWにも vert がありません。

そうするとどうなるかというと、UniGB-UTF16-V 経由で使った場合は縦組みグリフが出る、Unicode 指定で使った場合は横組み用グリフが出る（縦組み用グリフに切り替わらない）という現象になると思います。

plain XeTeX で確認したソースを示しておきます。

```.tex
% -*- coding: utf-8 mode:tex -*-

% for plain XeTeX

\font\fmh="[HaranoAjiMinchoTW-Regular.otf]" at 10pt
\font\fmv="[HaranoAjiMinchoTW-Regular.otf]:+vert" at 10pt
\font\fgh="[HaranoAjiGothicTW-Regular.otf]" at 10pt
\font\fgv="[HaranoAjiGothicTW-Regular.otf]:+vert" at 10pt

\fmh HaranoAjiMinchoTW

Direct CID

\XeTeXglyph121
\XeTeXglyph120

Unicode

^^^^2013

\fmv Unicode vert

^^^^2013

\fgh HaranoAjiGothicTW

Direct CID

\XeTeXglyph121
\XeTeXglyph120

Unicode

^^^^2013

\fgv Unicode vert

^^^^2013

\bye
```

**Comment by t-tk** [comment]
調査ありがとうございます。
HaranoAji{Mincho|Gothic}TW-Regular **20220211**
ここがポイントでした。

私のテストが HaranoAji TW 20220130 で行われていたせいでした。
20220211 ではU+2013は縦横とも横組みの字形が出力されました。つまり想定通りであることを確認しました。
お手数をかけてしまい済みませんでした。

**Comment by trueroad** [comment]
いずれにしましても、せっかくグリフがあるのに vert が無くて縦組みに切り替わらないのはもったいないので、vert が追加できないかは考えます。

**Comment by trueroad** [comment]
20220220版で vert を追加しました。
Unicode 指定でも U+2013 が縦組みグリフに切り替わると思います。

**Comment by t-tk** [comment]
ありがとうございます。
HaranoAji TW 20220220 で U+2013 が縦組みグリフに切り替わっていることを確認しました。

別件でU+2025 「‥」TWO DOT LEADER, U+2026「…」HORIZONTAL ELLIPSIS も戸惑いつつ納得したのでメモしておきます。
HaranoAji TW 20220220  かつ UniCNS-UTF16-{H,V} を使用したところ U+2025 は縦組みのときに縦組みグリフになり U+2026 は縦組みになりませんでした。
しかし、これは UniCNS-UTF16-V に U+2025 の指定はある一方 U+2026 の指定が無い所為でした。
韓国語 UniKS-UTF16-V も同様でした。
逆に、簡体字の UniGB-UTF16-V には  U+2026 の指定はある一方 U+2025 の指定が無いので U+2026 は縦組みのときに縦組みグリフになり U+2025 は縦組みになりませんでした。
ややこしいし直感に反していますが動作は正しいと納得しました。

**Comment by trueroad** [comment]
ご確認いただきありがとうございます。
